<?php
/**
 * @file
 * Site content creation and administration functionality.
 */

/**
 * Implements hook_admin_paths().
 */
function og_sm_content_admin_paths() {
  return array(
    'group/node/*/content/add' => TRUE,
    'group/node/*/content/add/*' => TRUE,
  );
}

/**
 * Implements hook_menu().
 */
function og_sm_content_menu() {
  $items = array();
  $file_admin = 'og_sm_content.admin.inc';
  $file_pages = 'og_sm_content.pages.inc';

  $items['group/%/%og_sm_site/admin/content'] = array(
    'title' => 'Administer content',
    'page callback' => 'og_sm_content_admin_overview',
    'page arguments' => array(2),
    'access callback' => 'og_sm_site_permission_access',
    'access arguments' => array(2, OG_SM_PERMISSION_SITE_ADMIN),
    'weight' => 11,
    'file' => $file_admin,
  );

  $items['group/%/%og_sm_site/admin/content/node'] = array(
    'title' => 'All content',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['group/%/%og_sm_site/admin/content/my'] = array(
    'title' => 'My content',
    'page callback' => 'og_sm_content_admin_overview_my',
    'page arguments' => array(2),
    'access callback' => 'og_sm_site_permission_access',
    'access arguments' => array(2, OG_SM_PERMISSION_SITE_ADMIN),
    'weight' => 10,
    'file' => $file_admin,
    'type' => MENU_LOCAL_TASK,
  );

  $items['group/%/%og_sm_site/admin/content/add'] = array(
    'title' => 'Add content',
    'page callback' => 'og_sm_content_admin_add_content',
    'page arguments' => array(2),
    'access callback' => 'og_sm_content_add_overview_access',
    'access arguments' => array(2),
    'weight' => 11,
    'file' => $file_admin,
    'type' => MENU_LOCAL_TASK,
  );

  $items['group/%/%og_sm_site/content/add'] = array(
    'title' => 'Add content',
    'page callback' => 'og_sm_content_add_overview',
    'page arguments' => array(2),
    'access callback' => 'og_sm_content_add_overview_access',
    'access arguments' => array(2),
    'weight' => 11,
    'file' => $file_pages,
    'type' => MENU_LOCAL_TASK,
  );

  // Add menu callbacks for all the Site content types.
  $base_path = 'group/%/%og_sm_site/content/add/';
  $types = og_sm_content_get_types();
  foreach ($types as $type) {
    $type_url_str = str_replace('_', '-', $type->type);
    $items[$base_path . $type_url_str] = array(
      'title' => $type->name,
      'title callback' => 'check_plain',
      'page callback' => 'og_sm_content_add_content',
      'page arguments' => array(2, $type->type),
      'access callback' => 'og_sm_content_add_content_access',
      'access arguments' => array(2, $type->type),
      'weight' => 11,
      'file' => $file_pages,
      'type' => MENU_LOCAL_TASK,
    );
  }

  return $items;
}

/**
 * Menu access callback for the admin/content/add page.
 *
 * This will check if the user has at least access to one Site content type.
 *
 * @param object $site
 *   The Site to check the access for.
 *
 * @return bool
 *   Has access.
 */
function og_sm_content_add_overview_access($site) {
  $types = og_sm_content_get_types_by_site($site);
  return !empty($types);
}

/**
 * Menu access callback for the admin/content/add/[type] page.
 *
 * This will check if the user has create access to the content type.
 *
 * @param object $site
 *   The Site to check the access for.
 * @param string $node_type
 *   The node type to check access for.
 *
 * @return bool
 *   Has access.
 */
function og_sm_content_add_content_access($site, $node_type) {
  $types = array_keys(og_sm_content_get_types_by_site($site));
  return in_array($node_type, $types);
}

/**
 * Implements hook_views_api().
 */
function og_sm_content_views_api() {
  return array("api" => "3.0");
}

/**
 * Get a list of Site content types by Site & (optional) Account.
 *
 * This will reduce the list of content types by the given site and the content
 * creation permissions of the given/current user account.
 *
 * @param object $site
 *   The Site node.
 * @param object $account
 *   (optional) User account to check access for.
 *
 * @return array
 *   The site type objects keyed by their type machine name.
 */
function og_sm_content_get_types_by_site($site, $account = NULL) {
  $types = array();

  $site_content_types = og_sm_content_get_types();
  foreach ($site_content_types as $site_content_type) {
    $permission = 'create ' . $site_content_type->type . ' content';
    if (!og_sm_site_permission_access($site, $permission, $account)) {
      continue;
    }

    $types[$site_content_type->type] = $site_content_type;
  }

  return $types;
}

/**
 * Helper to create a URL path to create a new content item.
 *
 * @param object $site
 *   The site to create the URL for.
 * @param string $node_type
 *   The node type to create.
 *
 * @return string
 *   The URI path.
 */
function og_sm_content_add_uri($site, $node_type) {
  $path = 'group/node/%d/content/add/%s';
  $nid = (int) $site->nid;
  $type = preg_replace('/_/', '-', $node_type);

  return sprintf($path, $nid, $type);
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function og_sm_content_admin_menu_output_alter(&$content) {
  $site = og_sm_current_site();

  // Only if there is an active Site.
  if (!$site || empty($content['#components']['og_sm_admin_menu.site'])) {
    return;
  }

  // Get the menu items to show.
  $items = og_sm_content_admin_menu_items($site);

  // Remove the node/add item if no items to show.
  if (!$items && isset($content['menu']['node/add'])) {
    unset($content['menu']['node/add']);
    return;
  }

  $content['menu']['node/add'] = $items;
}

/**
 * Helper to construct a menu of content create links for the admin menu.
 *
 * @param object $site
 *   The site to create the items for.
 *
 * @return array
 *   The menu items.
 */
function og_sm_content_admin_menu_items($site) {
  $items = array();
  $types = og_sm_content_get_types_by_site($site);
  if (!$types) {
    return $items;
  }

  $items = array(
    '#title' => t('Add content'),
    '#href' => url('group/node/' . $site->nid . '/content/add'),
    '#options' => array('alias' => TRUE),
    '#weight' => -100,
    '#attributes' => array('class' => array('admin-menu-toolbar-category')),
  );

  $weight = 1;
  foreach ($types as $type) {
    $key = 'node/add/' . $type->type;
    $sort[$type->name] = $key;
    $items[$key] = array(
      '#title' => $type->name,
      '#href' => url(og_sm_content_add_uri($site, $type->type)),
      '#options' => array(
        'attributes' => array(),
        'alias' => TRUE,
        'html' => TRUE,
      ),
      '#weight' => $weight,
    );
    $weight++;
  }

  return $items;
}

/**
 * Implements hook_url_outbound_alter().
 */
function og_sm_content_url_outbound_alter(&$path, &$options, $original_path) {
  // Rewrite all outgoing site admin paths for paths that do not have an alias.
  if (preg_match('#^group/node/([0-9]+)(/content.*)#', $path, $parts)) {
    $site = og_sm_site_load($parts[1]);
    if ($site) {
      $path = og_sm_site_path($site) . $parts[2];
    }
  }
}

/**
 * Implements hook_url_inbound_alter().
 */
function og_sm_content_url_inbound_alter(&$path, $original_path, $path_language) {
  // Translate an admin path without alias back to its original path.
  if (preg_match('#^([\w/_-]+)(/content.*)#', $path, $parts)) {
    $site = og_sm_site_load_by_path($parts[1]);
    if ($site) {
      $path = sprintf('group/node/%d%s', $site->nid, $parts[2]);
    }
  }
}
