<?php
/**
 * @file
 * Site content creation and administration functionality.
 */

// Permission access the site content type settings.
define('OG_SM_CONTENT_OG_PERM_ADMINISTER_CONTENT_TYPES', 'administer content types');

// Permission access the site content overview.
define('OG_SM_CONTENT_OG_PERM_ACCESS_CONTENT_OVERVIEW', 'access content overview');

// Permission access the site content overview.
define('OG_SM_CONTENT_OG_PERM_ACCESS_MY_CONTENT_OVERVIEW', 'access my content overview');

/**
 * Implements hook_hook_info().
 */
function og_sm_content_hook_info() {
  $hooks = array(
    'og_sm_content_type_info_alter' => array(
      'group' => 'og_sm',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_module_implements_alter().
 */
function og_sm_content_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['og_sm_content'];
    unset($implementations['og_sm_content']);
    $implementations['og_sm_content'] = $group;
  }
}

/**
 * Implements hook_admin_paths().
 */
function og_sm_content_admin_paths() {
  return array(
    'group/node/*/content/add' => TRUE,
    'group/node/*/content/add/*' => TRUE,
  );
}

/**
 * Implements hook_og_permission().
 */
function og_sm_content_og_permission() {
  return array(
    OG_SM_CONTENT_OG_PERM_ADMINISTER_CONTENT_TYPES => array(
      'title' => t('Administer content types'),
      'description' => t('Administer the Site content types.'),
      'roles' => array(OG_AUTHENTICATED_ROLE),
      'default role' => array(OG_ADMINISTRATOR_ROLE),
    ),
    OG_SM_CONTENT_OG_PERM_ACCESS_CONTENT_OVERVIEW => array(
      'title' => t('Access content overview'),
      'description' => t('Get an overview of all Site content.'),
      'roles' => array(OG_AUTHENTICATED_ROLE),
      'default role' => array(OG_ADMINISTRATOR_ROLE),
    ),
    OG_SM_CONTENT_OG_PERM_ACCESS_MY_CONTENT_OVERVIEW => array(
      'title' => t('Access my content overview page'),
      'description' => t('Get an overview of all Site content created by the current user.'),
      'roles' => array(OG_AUTHENTICATED_ROLE),
      'default role' => array(OG_ADMINISTRATOR_ROLE),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function og_sm_content_menu() {
  $items = array();
  $file_admin = 'og_sm_content.admin.inc';
  $file_pages = 'og_sm_content.pages.inc';

  $items['group/%/%og_sm_site/admin/content'] = array(
    'title' => 'Administer content',
    'page callback' => 'og_sm_content_admin_overview',
    'page arguments' => array(2),
    'access callback' => 'og_sm_site_permission_access',
    'access arguments' => array(2, OG_SM_CONTENT_OG_PERM_ACCESS_CONTENT_OVERVIEW),
    'weight' => 11,
    'file' => $file_admin,
  );

  $items['group/%/%og_sm_site/admin/content/node'] = array(
    'title' => 'All content',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['group/%/%og_sm_site/admin/content/my'] = array(
    'title' => 'My content',
    'page callback' => 'og_sm_content_admin_overview_my',
    'page arguments' => array(2),
    'access callback' => 'og_sm_site_permission_access',
    'access arguments' => array(2, OG_SM_CONTENT_OG_PERM_ACCESS_MY_CONTENT_OVERVIEW),
    'weight' => 10,
    'file' => $file_admin,
    'type' => MENU_LOCAL_TASK,
  );

  $items['group/%/%og_sm_site/admin/content/add'] = array(
    'title' => 'Add content',
    'page callback' => 'og_sm_content_admin_add_content',
    'page arguments' => array(2),
    'access callback' => 'og_sm_content_add_overview_access',
    'access arguments' => array(2),
    'weight' => 11,
    'file' => $file_admin,
    'type' => MENU_LOCAL_TASK,
  );

  $items['group/%/%og_sm_site/admin/structure/types'] = array(
    'title' => 'Administer content types',
    'page callback' => 'og_sm_content_admin_overview_types',
    'page arguments' => array(2),
    'access callback' => 'og_sm_site_permission_access',
    'access arguments' => array(2, OG_SM_CONTENT_OG_PERM_ADMINISTER_CONTENT_TYPES),
    'file' => $file_admin,
  );

  $items['group/%/%og_sm_site/content/add'] = array(
    'title' => 'Add content',
    'page callback' => 'og_sm_content_add_overview',
    'page arguments' => array(2),
    'access callback' => 'og_sm_content_add_overview_access',
    'access arguments' => array(2),
    'weight' => 11,
    'file' => $file_pages,
    'type' => MENU_LOCAL_TASK,
  );

  // Add menu callbacks for all the Site content types.
  $base_add_content_path = 'group/%/%og_sm_site/content/add/';
  $base_adminster_type_path = 'group/%/%og_sm_site/admin/structure/types/';
  $types = og_sm_content_get_types();
  foreach ($types as $type) {
    $type_url_str = str_replace('_', '-', $type->type);
    $items[$base_add_content_path . $type_url_str] = array(
      'title' => $type->name,
      'title callback' => 'check_plain',
      'page callback' => 'og_sm_content_add_content',
      'page arguments' => array(2, $type->type),
      'access callback' => 'og_sm_content_add_content_access',
      'access arguments' => array(2, $type->type),
      'weight' => 11,
      'file' => $file_pages,
      'type' => MENU_LOCAL_TASK,
    );

    $items[$base_adminster_type_path . $type_url_str] = array(
      'title' => $type->name,
      'title callback' => 'check_plain',
      'page callback' => 'drupal_get_form',
      'page arguments' => array(
        'og_sm_content_admin_overview_type_edit_form',
        2,
        6,
      ),
      'access callback' => 'og_sm_site_permission_access',
      'access arguments' => array(2, OG_SM_CONTENT_OG_PERM_ADMINISTER_CONTENT_TYPES),
      'file' => $file_admin,
    );
  }

  return $items;
}

/**
 * Implements hook_node_access().
 *
 * We are adding our own hook_node_access implementation since we don't want
 * site members to be able to access the global node add/edit forms.
 */
function og_sm_content_node_access($node, $op, $account) {
  // We only have to check create, other options are already covered.
  if ($op !== 'create') {
    return NODE_ACCESS_IGNORE;
  }

  // The node property is always a string when op(eration) = create.
  $type = $node;

  // We don't want to intervene if this is not a site content type.
  if (!og_sm_content_is_site_content_type($type)) {
    return NODE_ACCESS_IGNORE;
  }

  // We want to fetch the context from the path rather then the node since we
  // don't want to give citizen access to the global node edit forms.
  $site = og_sm_current_site();

  // If we are within a site context we let og_node_access verify the access.
  if ($site) {
    return NODE_ACCESS_IGNORE;
  }

  // Since og_node_access will return NODE_ACCESS_ALLOW, we need to make sure
  // that that the result of node_node_access is interpreted as a
  // NODE_ACCESS_DENY rather then a NODE_ACCESS_IGNORE. node_node_access will
  // only check the global permissions.
  if (node_node_access($node, $op, $account) === NODE_ACCESS_IGNORE) {
    return NODE_ACCESS_DENY;
  }

  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_menu_alter().
 */
function og_sm_content_menu_alter(&$items) {
  // Add support for the addanother module.
  $path = 'node/%node/addanother';
  if (isset($items[$path])) {
    $items[$path]['page callback'] = 'og_sm_content_addanother_goto';
    $items[$path]['file'] = 'modules/addanother.inc';
  }
}

/**
 * Menu access callback for the admin/content/add page.
 *
 * This will check if the user has at least access to one Site content type.
 *
 * @param object $site
 *   The Site to check the access for.
 *
 * @return bool
 *   Has access.
 */
function og_sm_content_add_overview_access($site) {
  $types = og_sm_content_get_types_by_site($site);
  return !empty($types);
}

/**
 * Menu access callback for the admin/content/add/[type] page.
 *
 * This will check if the user has create access to the content type.
 *
 * @param object $site
 *   The Site to check the access for.
 * @param string $node_type
 *   The node type to check access for.
 * @param object $account
 *   (optional) User account to check access for.
 *
 * @return bool
 *   Has access.
 */
function og_sm_content_add_content_access($site, $node_type, $account = NULL) {
  $types = array_keys(og_sm_content_get_types_by_site($site, $account));
  return in_array($node_type, $types);
}

/**
 * Implements hook_views_api().
 */
function og_sm_content_views_api() {
  return array("api" => "3.0");
}

/**
 * Get a list of Site content types by Site & (optional) Account.
 *
 * This will reduce the list of content types by the given site and the content
 * creation permissions of the given/current user account.
 *
 * @param object $site
 *   The Site node.
 * @param object $account
 *   (optional) User account to check access for.
 *
 * @return array
 *   The site type objects keyed by their type machine name.
 */
function og_sm_content_get_types_by_site($site, $account = NULL) {
  $types = array();

  $site_content_types = og_sm_content_get_types();
  foreach ($site_content_types as $site_content_type) {
    $permission = 'create ' . $site_content_type->type . ' content';
    if (!og_sm_site_permission_access($site, $permission, $account)) {
      continue;
    }
    $types[$site_content_type->type] = og_sm_content_get_type_info_by_site($site, $site_content_type);
  }

  return $types;
}

/**
 * Fetches the site specific settings for a content type.
 *
 * @param object $site
 *   The Site node.
 * @param object|string $content_type
 *   The content type object or machine name.
 *
 * @return object|FALSE
 *   The site specific content type object.
 *   FALSE if the content type machine name does not exists.
 */
function og_sm_content_get_type_info_by_site($site, $content_type) {
  if (is_string($content_type)) {
    $content_type = node_type_load($content_type);
  }
  if (!$content_type) {
    FALSE;
  }

  $infos = &drupal_static(__FUNCTION__, array());
  $key = sprintf('%s:%d', $content_type->type, $site->nid);

  if (!isset($infos[$key])) {
    // We create a clone of the original record to avoid altering the data in
    // the global content type cache.
    $type_info = clone $content_type;
    drupal_alter('og_sm_content_type_info', $type_info, $site);
    $infos[$key] = $type_info;
  }

  return $infos[$key];
}

/**
 * Fetches the site specific settings for a content type.
 *
 * @param object $node
 *   The node to fetch the site specific content type info of.
 *
 * @return object|FALSE
 *   The site specific content type object.
 */
function og_sm_content_get_type_info_by_node($node) {
  if (!og_sm_content_is_site_content($node)) {
    return FALSE;
  }
  $site = og_sm_content_get_site($node);
  if ($site) {
    return og_sm_content_get_type_info_by_site($site, $node->type);
  }
  return FALSE;
}

/**
 * Fetches the original content type name based on the site specific alias.
 *
 * @param object $site
 *   The Site node.
 * @param string $content_type
 *   The site specific content type alias.
 *
 * @return string|FALSE
 *   The original content type name, FALSE if no match was found.
 */
function og_sm_content_get_original_type_by_site_alias_type($site, $content_type) {
  $site_content_types = og_sm_content_get_types();
  foreach ($site_content_types as $site_content_type) {
    $site_content_type = og_sm_content_get_type_info_by_site($site, $site_content_type);
    if ($site_content_type->site_type === $content_type) {
      return $site_content_type->type;
    }
  }
  return FALSE;
}

/**
 * Helper to create a URL path to create a new content item.
 *
 * @param object $site
 *   The site to create the URL for.
 * @param string $node_type
 *   The node type to create.
 *
 * @return string
 *   The URI path.
 */
function og_sm_content_add_uri($site, $node_type) {
  $path = 'group/node/%d/content/add/%s';
  $nid = (int) $site->nid;
  $type = preg_replace('/_/', '-', $node_type);

  return sprintf($path, $nid, $type);
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function og_sm_content_admin_menu_output_alter(&$content) {
  $site = og_sm_current_site();

  // Only if there is an active Site.
  if (!$site || empty($content['#components']['og_sm_admin_menu.site'])) {
    return;
  }

  // Only if there are node/add menu's.
  if (empty($content['menu']['node/add'])
    && empty($content['responsive-menu']['node/add'])
  ) {
    return;
  }

  // Get the menu items to show.
  $items = og_sm_content_admin_menu_items($site);

  // Update desktop & responsive menu.
  $menu_types = array('menu', 'responsive-menu');
  foreach ($menu_types as $menu_type) {
    // Only if the menu item exists.
    if (!isset($content[$menu_type]['node/add'])) {
      continue;
    }

    // Remove if no items.
    if (empty($items)) {
      unset($content[$menu_type]['node/add']);
      continue;
    }

    $content[$menu_type]['node/add'] = $items;
  }
}

/**
 * Helper to construct a menu of content create links for the admin menu.
 *
 * @param object $site
 *   The site to create the items for.
 *
 * @return array
 *   The menu items.
 */
function og_sm_content_admin_menu_items($site) {
  $items = array();
  $types = og_sm_content_get_types_by_site($site);
  if (!$types) {
    return $items;
  }

  $items = array(
    '#title' => t('Add content'),
    '#href' => url('group/node/' . $site->nid . '/content/add'),
    '#options' => array('alias' => TRUE),
    '#weight' => -100,
    '#attributes' => array('class' => array('admin-menu-toolbar-category')),
  );

  $weight = 1;
  foreach ($types as $type) {
    $path = og_sm_content_add_uri($site, $type->type);

    // Checks a path exists and the current user has access to it.
    if (!drupal_valid_path($path)) {
      continue;
    }

    $key = 'node/add/' . $type->type;
    $sort[$type->name] = $key;
    $items[$key] = array(
      '#title' => $type->name,
      '#href' => url($path),
      '#options' => array(
        'attributes' => array(),
        'alias' => TRUE,
        'html' => TRUE,
      ),
      '#weight' => $weight,
    );
    $weight++;
  }

  return $items;
}

/**
 * Implements hook_url_outbound_alter().
 */
function og_sm_content_url_outbound_alter(&$path, &$options, $original_path) {
  $site = FALSE;
  // Rewrite all path which have the node type name in them, try to replace it
  // with the site specific content type name.
  if (preg_match('#^group/node/([0-9]+)(/content/add/|/admin/structure/types/)([a-z0-9_\-]*)#', $path, $parts)) {
    if ($site = og_sm_site_load($parts[1])) {
      $content_type = og_sm_content_get_type_info_by_site($site, $parts[3]);
      $type_name = (!$content_type)
        ? $parts[3]
        : $content_type->site_type;

      $content_type_name = drupal_html_class($type_name);
      $path = str_replace($parts[3], $content_type_name, $path);
    }
  }
  // Support for og_sm_path module:
  // Rewrite all outgoing site admin paths for paths that do not have an alias.
  if (module_exists('og_sm_path') && preg_match('#^group/node/([0-9]+)(/content.*)#', $path, $parts)) {
    $site = $site ?: og_sm_site_load($parts[1]);
    if ($site) {
      $path = og_sm_path($site) . $parts[2];
    }
  }
}

/**
 * Implements hook_url_inbound_alter().
 */
function og_sm_content_url_inbound_alter(&$path, $original_path, $path_language) {
  $site = FALSE;
  // Support for og_sm_path module:
  // Translate an admin path without alias back to its original path.
  if (module_exists('og_sm_path') && preg_match('#^([\w/_-]+)(/content.*)#', $path, $parts)) {
    $site = og_sm_path_load_site($parts[1]);
    if ($site) {
      $path = sprintf('group/node/%d%s', $site->nid, $parts[2]);
    }
  }
  // Translate site specific node type paths back to their original path.
  if (preg_match('#^group/node/([0-9]+)(/content/add/|/admin/structure/types/)([a-z0-9_\-]*)#', $path, $parts)) {
    $site = $site ?: og_sm_site_load($parts[1]);
    if ($site) {
      $alias_type_name = str_replace('-', '_', $parts[3]);
      $node_type_name = og_sm_content_get_original_type_by_site_alias_type($site, $alias_type_name);
      $node_type_name = str_replace('_', '-', $node_type_name);
      $path = str_replace($parts[3], $node_type_name, $path);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function og_sm_content_form_alter(&$form, &$form_state, $form_id) {
  // Add support for addanother module buttons within a Site context.
  if (isset($form['actions']['addanother'])) {
    form_load_include($form_state, 'inc', 'og_sm_content', 'modules/addanother');
    og_sm_content_form_alter_addanother($form, $form_state);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function og_sm_content_form_node_form_alter(&$form, &$form_state, $form_id) {
  // Only alter node forms in a Site context.
  $site = og_sm_current_site();
  if (!$site) {
    return;
  }

  // Only if there is Site specific info (= is Site content type).
  $node = $form_state['node'];
  $content_type_info = og_sm_content_get_type_info_by_site($site, $node->type);
  if (!$content_type_info) {
    return;
  }

  // Normally the permission "administer nodes" is required to change the node
  // author, options, etc. That global role might not be granted in a Site
  // context. We add an extra check on the Site role "administer site" to allow
  // access to these fields.
  $access = user_access('administer nodes') || og_sm_site_permission_access($site, 'administer site');
  if (isset($form['revision_information'])) {
    $form['revision_information']['#access'] = $node->revision || $access;
    $form['revision_information']['revision']['#access'] = $access;
  }
  if (isset($form['author'])) {
    $form['author']['#access'] = $access;
  }
  if (isset($form['options'])) {
    $form['options']['#access'] = $access;
  }

  // Make sure the content type name alias is used on the node add/edit form.
  if (empty($node->nid)) {
    drupal_set_title(t('Create @name', array('@name' => $content_type_info->name)), PASS_THROUGH);
  }
  else {
    $args = array(
      '@type' => $content_type_info->name,
      '@title' => $node->title,
    );
    drupal_set_title(t('<em>Edit @type</em> @title', $args), PASS_THROUGH);
  }
}
