<?php
/**
 * @file
 * Site taxonomy support.
 */

/**
 * Get all vocabulary names that have OG group field.
 *
 * @return array
 *   Vocabularies grouped by their machine name.
 */
function og_sm_taxonomy_get_vocabularies() {
  $vocabularies = array();

  $bundles = og_get_all_group_content_bundle();
  if (empty($bundles['taxonomy_term'])) {
    return $vocabularies;
  }

  $bundles = array_keys($bundles['taxonomy_term']);
  foreach ($bundles as $bundle) {
    $vocabularies[$bundle] = taxonomy_vocabulary_machine_name_load($bundle);
  }
  return $vocabularies;
}

/**
 * Check if a given taxonomy vocabulary is an OG vocabulary.
 *
 * @param string $name
 *   The vocbulary name.
 *
 * @return bool
 *   Is an OG vocabulary.
 */
function og_sm_taxonomy_is_vocabulary($name) {
  $bundles = og_get_all_group_content_bundle();
  if (empty($bundles['taxonomy_term'])) {
    return FALSE;
  }

  return array_key_exists($name, $bundles['taxonomy_term']);
}
