<?php

/**
 * @file
 * Site menu module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\og_menu\OgMenuInstanceInterface;

/**
 * Implements hook_entity_insert().
 */
function og_sm_menu_entity_insert(EntityInterface $entity) {
  // When a site menu is created we should rebuild the menu tree to make sure
  // our site menu items linked to the site show up.
  if ($entity instanceof OgMenuInstanceInterface) {
    \Drupal::service('plugin.manager.menu.link')->rebuild();
  }
}
