<?php

/**
 * @file
 * Base module for the Organic Groups Sites functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\og_sm\OgSm;
use Drupal\og_sm\Event\SiteEvents;
use Zend\Diactoros\Exception\DeprecatedMethodException;

/**
 * Implements hook_hook_info().
 */
function og_sm_hook_info() {
  $group = array('group' => 'og_sm');

  $hooks = array(
    'og_sm_site_view' => $group,
    'og_sm_site_homepage_alter' => $group,
  );

  return $hooks;
}

/**
 * Implements hook_form_FORM_ID_alter() for node_type_form().
 */
function og_sm_form_node_type_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form_state->loadInclude('og_sm', 'inc', 'og_sm.admin');
  _og_sm_form_node_type_form_alter($form, $form_state);
}

/**
 * Set the breadcrumb for the given Site.
 *
 * @todo: Check if this is still needed.
 *
 * @param object $site
 *   The site object to setthe breadcrumb for.
 * @param array $path
 *   Array of links to append to the breadcumb.
 *
 * @deprecated in Drupal 8.x and will be removed before stable release.
 */
function og_sm_set_breadcrumb($site, $path = array()) {
  throw new DeprecatedMethodException('og_sm_set_breadcrumb() still needs to be ported.');
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function og_sm_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  // Only for Site node types.
  if (!OgSm::isSite($node)) {
    return;
  }
  Drupal::moduleHandler()->invokeAll('og_sm_site_view', [$build, $node, $display, $view_mode]);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for node entities.
 */
function og_sm_node_delete(NodeInterface $node) {
  OgSm::siteEventDispatch(SiteEvents::DELETE, $node);
}

/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 */
function og_sm_node_presave(NodeInterface $node) {
  OgSm::siteEventDispatch(SiteEvents::PRESAVE, $node);
}

/**
 * Implements hook_ENTITY_TYPE_update() for node entities.
 */
function og_sm_node_update(NodeInterface $node) {
  OgSm::siteEventDispatch(SiteEvents::UPDATE, $node);
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 */
function og_sm_node_insert(NodeInterface $node) {
  OgSm::siteEventDispatch(SiteEvents::INSERT, $node);
}
