<?php
/**
 * @file
 * Module to support Site paths.
 */

/**
 * Implements hook_form_FORMID_alter().
 *
 * Adds the Site Path field to the Site node forms.
 */
function og_sm_path_form_node_form_alter(&$form, &$form_state) {
  if (og_sm_is_site($form['#node'])) {
    form_load_include($form_state, 'inc', 'og_sm_path', 'og_sm_path.form');
    _og_sm_path_form_node_site_form_alter($form, $form_state);
  }
}

/**
 * Implements hook_og_sm_site_insert().
 */
function og_sm_path_og_sm_site_insert($site) {
  // Save the Site path.
  og_sm_variable_set($site->nid, 'path', $site->site_path);
}

/**
 * Implements hook_og_sm_site_update().
 */
function og_sm_path_og_sm_site_update($site) {
  // Save the Site path.
  og_sm_variable_set($site->nid, 'path', $site->site_path);
}
