<?php
/**
 * @file
 * Module to automatically create aliases for Site related paths.
 */

/**
 * Implements hook_og_sm_site_update_alias().
 */
function og_sm_pathauto_og_sm_site_update_alias($site) {
  // Update all aliases for the Site when its alias changes.
  module_load_include('inc', 'og_sm_pathauto', 'og_sm_pathauto.batch');
  og_sm_pathauto_site_alias_update_batch($site);
}

/**
 * Implements hook_og_sm_site_delete().
 */
function og_sm_pathauto_og_sm_site_delete($site) {
  // Delete all aliases for a site when it is deleted.
  og_sm_pathauto_site_delete_aliases($site);
}

/**
 * Delete all aliases for the given Site.
 *
 * @param object $site
 *   The Site node to delete the aliases for.
 */
function og_sm_pathauto_site_delete_aliases($site) {
  $site_path = og_sm_site_path($site);
  db_delete('url_alias')
    ->condition('alias', db_like($site_path) . '/%', 'LIKE')
    ->execute();
}

/**
 * Implements hook_url_outbound_alter().
 */
function og_sm_pathauto_url_outbound_alter(&$path, &$options, $original_path) {
  // Rewrite all outgoing site admin paths for paths that do not have an alias.
  if (preg_match('#^group/node/([0-9]+)(/admin.*)#', $path, $parts)) {
    $site = og_sm_site_load($parts[1]);
    if ($site) {
      $path = og_sm_site_path($site) . $parts[2];
    }
  }

  // This will check replace any destination (in the options > query) by its
  // path alias.
  if (isset($options['query']['destination'])) {
    $alias = url($options['query']['destination']);
    $options['query']['destination'] = trim($alias, '/');
  }
}

/**
 * Implements hook_url_inbound_alter().
 */
function og_sm_pathauto_url_inbound_alter(&$path, $original_path, $path_language) {
  // Translate an admin path without alias back to its original path.
  if (preg_match('#^([\w/_-]+)(/admin.*)#', $path, $parts)) {
    $site = og_sm_site_load_by_path($parts[1]);
    if ($site) {
      $path = sprintf('group/node/%d%s', $site->nid, $parts[2]);
    }
  }
}
